### ISSUE TITLE
Debug build on Nuget

### ISSUE THREAD

**Issue by rvost** [FlipperPlz/BisUtils#8]
I found that you probably accidentally uploaded debug build of  `BisUtils.Core` to Nuget.org. I discovered this while running a benchmark (`BenchmarkDotNet` threw a validation error), so I have some number to highlight the problem: 

![CompressionBenchmarks](https://user-images.githubusercontent.com/48875452/236289995-e7583a8d-a3aa-491b-971c-ea46e3570475.png)

`FPackerCompressini` is roughly the same code (from fork of your `FPacker` repo) but built with release config, and as you can see it approx. 15 times faster.

As far as I know, this happened with the `net7.0` version of `BisUtils.Core`, but other packages may have the same problem.

**Comment by FlipperPlz** [comment]
I will be closing this issue for now as I don't plan on updating nuget releases until we have a stable library (I would say around version 1.0 with BisUtils.Bank and ConfigCPP parsing finished). Again sorry for the late reply as this project was neglected for a short while.
